name: Sync Docker Images to Aliyun ACR
run-name: ${{ github.actor }} is syncing Docker images


on:
  push:
    branches:
      - main
    paths:
      - 'images.txt'
      - '.github/workflows/sync.yml'
  workflow_dispatch:

jobs:
  sync-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Aliyun Container Registry (ACR)
        uses: docker/login-action@v3
        with:
          registry: 'crpi-mtq8m566nr3q25lz.cn-hangzhou.personal.cr.aliyuncs.com'
          username: 'user_jxm'
          password: 'jxmloveyou199104'

      - name: Execute sync script
        run: |
          bash "${{ github.workspace }}/sync.sh"
        env:
          ACR_REGISTRY: 'crpi-mtq8m566nr3q25lz.cn-hangzhou.personal.cr.aliyuncs.com'
          ACR_NAMESPACE: 'dockerk3s'

      - name: Job status
        run: echo "This job's status is ${{ job.status }}"
